name: NoxRadarJammer
version: ${project.version}
author: bbcsto13
authors: [Coaster3000, bbcsto13]
main: ${main}
depend: [ProtocolLib]
softpend: [BKCommonLib, HoloAPI, NoxCore]
website: http://www.noxpvp.com
commands:
  radar:
    aliases: [radarjammer, jammer, rj]
    description: Displays the help menu for the RadarJammer
    usage: /<command>