name: NoxRadarJammer
version: ${project.version}
authors: [Coaster3000, bbcsto13]
main: ${main}
depend: [BKCommonLib]
commands:
  radar:
    aliases: [radarjammer, jammer, rj]
    description: Displays the help menu for the RadarJammer
    usage: /<command>